language: go
dist: focal
go: 
  - 1.17.1
  - tip
env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
sudo: required
install:
  - go get github.com/logingood/cni-ipam-consul
script: 
  - ./test
notifications:
  email: false
