#!/usr/bin/env bash

set -e

ORG_PATH="github.com/logingood"
REPO_PATH="${ORG_PATH}/cni-ipam-consul"

go get github.com/onsi/gomega
go get github.com/onsi/ginkgo

go build $REPO_PATH

#sudo -E bash -c "umask 0; PATH=$GOROOT/bin:$GOBIN:$PATH go test -covermode set $REPO_PATH"
